version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-us-east-1-852831150055 --output-template-file packaged-template.yaml
  install:
    runtime-versions:
      python: 3.7

artifacts:
  files:
    - template.yaml
    - packaged-template.yaml
